# Configuration for https://goreleaser.com/
project_name: authenticator

git:
  short_hash: true

builds:
  - binary: aws-iam-authenticator
    main: ./cmd/aws-iam-authenticator/
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"

dockers:
  - image: gcr.io/heptio-images/authenticator
    binary: aws-iam-authenticator
    dockerfile: Dockerfile.scratch
    tag_templates:
     - "{{ .Tag }}-scratch"
     - "{{ .Tag }}"
    latest: false
  - image: gcr.io/heptio-images/authenticator
    binary: aws-iam-authenticator
    dockerfile: Dockerfile.alpine-3.6
    tag_templates:
     - "{{ .Tag }}-alpine-3.6"
    latest: false
  - image: gcr.io/heptio-images/authenticator
    binary: aws-iam-authenticator
    dockerfile: Dockerfile.alpine-3.7
    tag_templates:
     - "{{ .Tag }}-alpine-3.7"
     - "{{ .Tag }}-alpine"
    latest: false
  - image: gcr.io/heptio-images/authenticator
    binary: aws-iam-authenticator
    dockerfile: Dockerfile.debian-jessie
    tag_templates:
     - "{{ .Tag }}-debian-jessie"
    latest: false
  - image: gcr.io/heptio-images/authenticator
    binary: aws-iam-authenticator
    dockerfile: Dockerfile.debian-stretch
    tag_templates:
     - "{{ .Tag }}-debian-stretch"
     - "{{ .Tag }}-debian"
    latest: false

snapshot:
  name_template: "git-{{.Commit}}"

archive:
  format: binary

release:
  github:
    owner: heptio
    name: authenticator
  draft: true
  prerelease: true
  name_template: "v{{.Version}}"
